blank_issues_enabled: true
contact_links:
    - name: General Question
      url: https://github.com/liatrio-labs/liatrio-wave/discussions
      about: Have a question on something? Start a new discussion thread.
    - name: Engage with Liatrio
      url: https://www.liatrio.com/contact
      about: Contact Liatrio for enterprise support and consulting.
    - name: Review open issues
      url: https://github.com/liatrio-labs/liatrio-wave/issues
      about: Please check if your issue isn't already there.
